# This is a basic workflow to help you get started with Actions

name: Go

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tmate:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          release: false
          update: true
          install: git
      - name: tmate
        uses: mxschmitt/action-tmate@v3.1
